import type * as aws from '@pulumi/aws';

import { defineInjectable, defineInterface, defineService, envVariable } from '@nzyme/ioc';

/**
 * AWS provider options.
 */
export interface AwsConfig {
    /**
     * Region.
     */
    region: aws.Region;

    /**
     * Access key.
     */
    accessKey?: string;

    /**
     * Secret key.
     */
    secretKey?: string;

    /**
     * Profile name.
     */
    profile?: string;

    /**
     * Skip credentials validation.
     */
    skipCredentialsValidation?: boolean;

    /**
     * Skip requesting account ID.
     */
    skipRequestingAccountId?: boolean;

    /**
     * Use path style for S3.
     */
    s3UsePathStyle?: boolean;

    /**
     * Endoints.
     */
    endpoints?: aws.types.input.ProviderEndpoint;
}

/**
 * AWS config.
 */
export const AwsConfig = defineInterface<AwsConfig>({
    name: 'AwsConfig',
    default: defineInjectable({
        name: 'AwsConfig',
        resolve: () => {
            return {
                region: (process.env.AWS_REGION as aws.Region | undefined) ?? 'eu-central-1',
                accessKey: process.env.AWS_ACCESS_KEY_ID,
                secretKey: process.env.AWS_SECRET_ACCESS_KEY,
                profile: process.env.AWS_PROFILE,
            };
        },
    }),
});

/**
 * AWS config for localstack.
 */
export const AwsConfigLocalStack = defineService({
    name: 'AwsConfigLocalStack',
    implements: AwsConfig,
    deps: {
        port: envVariable('LOCALSTACK_PORT'),
        region: envVariable('AWS_REGION'),
        accessKey: envVariable('AWS_ACCESS_KEY_ID'),
        secretKey: envVariable('AWS_SECRET_ACCESS_KEY'),
    },
    setup: opts => {
        const endpoint = `http://localhost:${opts.port ?? 4566}`;

        return {
            region: (opts.region as aws.Region) ?? 'eu-central-1',
            accessKey: opts.accessKey ?? 'test',
            secretKey: opts.secretKey ?? 'test',
            skipCredentialsValidation: true,
            skipRequestingAccountId: true,
            s3UsePathStyle: true,
            endpoints: {
                accessanalyzer: endpoint,
                account: endpoint,
                acm: endpoint,
                acmpca: endpoint,
                amg: endpoint,
                amp: endpoint,
                amplify: endpoint,
                apigateway: endpoint,
                apigatewayv2: endpoint,
                appautoscaling: endpoint,
                appconfig: endpoint,
                appfabric: endpoint,
                appflow: endpoint,
                appintegrations: endpoint,
                appintegrationsservice: endpoint,
                applicationautoscaling: endpoint,
                applicationinsights: endpoint,
                appmesh: endpoint,
                appregistry: endpoint,
                apprunner: endpoint,
                appstream: endpoint,
                appsync: endpoint,
                athena: endpoint,
                auditmanager: endpoint,
                autoscaling: endpoint,
                autoscalingplans: endpoint,
                backup: endpoint,
                batch: endpoint,
                beanstalk: endpoint,
                bedrock: endpoint,
                bedrockagent: endpoint,
                budgets: endpoint,
                ce: endpoint,
                chime: endpoint,
                chimesdkmediapipelines: endpoint,
                chimesdkvoice: endpoint,
                cleanrooms: endpoint,
                cloud9: endpoint,
                cloudcontrol: endpoint,
                cloudcontrolapi: endpoint,
                cloudformation: endpoint,
                cloudfront: endpoint,
                cloudfrontkeyvaluestore: endpoint,
                cloudhsm: endpoint,
                cloudhsmv2: endpoint,
                cloudsearch: endpoint,
                cloudtrail: endpoint,
                cloudwatch: endpoint,
                cloudwatchevents: endpoint,
                cloudwatchevidently: endpoint,
                cloudwatchlog: endpoint,
                cloudwatchlogs: endpoint,
                cloudwatchobservabilityaccessmanager: endpoint,
                cloudwatchrum: endpoint,
                codeartifact: endpoint,
                codebuild: endpoint,
                codecatalyst: endpoint,
                codecommit: endpoint,
                codedeploy: endpoint,
                codeguruprofiler: endpoint,
                codegurureviewer: endpoint,
                codepipeline: endpoint,
                codestarconnections: endpoint,
                codestarnotifications: endpoint,
                cognitoidentity: endpoint,
                cognitoidentityprovider: endpoint,
                cognitoidp: endpoint,
                comprehend: endpoint,
                computeoptimizer: endpoint,
                config: endpoint,
                configservice: endpoint,
                connect: endpoint,
                connectcases: endpoint,
                controltower: endpoint,
                costandusagereportservice: endpoint,
                costexplorer: endpoint,
                costoptimizationhub: endpoint,
                cur: endpoint,
                customerprofiles: endpoint,
                databasemigration: endpoint,
                databasemigrationservice: endpoint,
                dataexchange: endpoint,
                datapipeline: endpoint,
                datasync: endpoint,
                dax: endpoint,
                deploy: endpoint,
                detective: endpoint,
                devicefarm: endpoint,
                directconnect: endpoint,
                directoryservice: endpoint,
                dlm: endpoint,
                dms: endpoint,
                docdb: endpoint,
                docdbelastic: endpoint,
                ds: endpoint,
                dynamodb: endpoint,
                ec2: endpoint,
                ecr: endpoint,
                ecrpublic: endpoint,
                ecs: endpoint,
                efs: endpoint,
                eks: endpoint,
                elasticache: endpoint,
                elasticbeanstalk: endpoint,
                elasticloadbalancing: endpoint,
                elasticloadbalancingv2: endpoint,
                elasticsearch: endpoint,
                elasticsearchservice: endpoint,
                elastictranscoder: endpoint,
                elb: endpoint,
                elbv2: endpoint,
                emr: endpoint,
                emrcontainers: endpoint,
                emrserverless: endpoint,
                es: endpoint,
                eventbridge: endpoint,
                events: endpoint,
                evidently: endpoint,
                finspace: endpoint,
                firehose: endpoint,
                fis: endpoint,
                fms: endpoint,
                fsx: endpoint,
                gamelift: endpoint,
                glacier: endpoint,
                globalaccelerator: endpoint,
                glue: endpoint,
                grafana: endpoint,
                greengrass: endpoint,
                groundstation: endpoint,
                guardduty: endpoint,
                healthlake: endpoint,
                iam: endpoint,
                identitystore: endpoint,
                imagebuilder: endpoint,
                inspector: endpoint,
                inspector2: endpoint,
                inspectorv2: endpoint,
                internetmonitor: endpoint,
                iot: endpoint,
                iotanalytics: endpoint,
                iotevents: endpoint,
                ivs: endpoint,
                ivschat: endpoint,
                kafka: endpoint,
                kafkaconnect: endpoint,
                kendra: endpoint,
                keyspaces: endpoint,
                kinesis: endpoint,
                kinesisanalytics: endpoint,
                kinesisanalyticsv2: endpoint,
                kinesisvideo: endpoint,
                kms: endpoint,
                lakeformation: endpoint,
                lambda: endpoint,
                launchwizard: endpoint,
                lex: endpoint,
                lexmodelbuilding: endpoint,
                lexmodelbuildingservice: endpoint,
                lexmodels: endpoint,
                lexmodelsv2: endpoint,
                lexv2models: endpoint,
                licensemanager: endpoint,
                lightsail: endpoint,
                location: endpoint,
                locationservice: endpoint,
                logs: endpoint,
                lookoutmetrics: endpoint,
                m2: endpoint,
                macie2: endpoint,
                managedgrafana: endpoint,
                mediaconnect: endpoint,
                mediaconvert: endpoint,
                medialive: endpoint,
                mediapackage: endpoint,
                mediapackagev2: endpoint,
                mediastore: endpoint,
                memorydb: endpoint,
                mq: endpoint,
                msk: endpoint,
                mwaa: endpoint,
                neptune: endpoint,
                networkfirewall: endpoint,
                networkmanager: endpoint,
                oam: endpoint,
                opensearch: endpoint,
                opensearchingestion: endpoint,
                opensearchserverless: endpoint,
                opensearchservice: endpoint,
                opsworks: endpoint,
                organizations: endpoint,
                osis: endpoint,
                outposts: endpoint,
                pcaconnectorad: endpoint,
                pinpoint: endpoint,
                pipes: endpoint,
                polly: endpoint,
                pricing: endpoint,
                prometheus: endpoint,
                prometheusservice: endpoint,
                qbusiness: endpoint,
                qldb: endpoint,
                quicksight: endpoint,
                ram: endpoint,
                rbin: endpoint,
                rds: endpoint,
                recyclebin: endpoint,
                redshift: endpoint,
                redshiftdata: endpoint,
                redshiftdataapiservice: endpoint,
                redshiftserverless: endpoint,
                rekognition: endpoint,
                resourceexplorer2: endpoint,
                resourcegroups: endpoint,
                resourcegroupstagging: endpoint,
                resourcegroupstaggingapi: endpoint,
                rolesanywhere: endpoint,
                route53: endpoint,
                route53domains: endpoint,
                route53recoverycontrolconfig: endpoint,
                route53recoveryreadiness: endpoint,
                route53resolver: endpoint,
                rum: endpoint,
                s3: endpoint,
                s3api: endpoint,
                s3control: endpoint,
                s3outposts: endpoint,
                sagemaker: endpoint,
                scheduler: endpoint,
                schemas: endpoint,
                sdb: endpoint,
                secretsmanager: endpoint,
                securityhub: endpoint,
                securitylake: endpoint,
                serverlessapplicationrepository: endpoint,
                serverlessapprepo: endpoint,
                serverlessrepo: endpoint,
                servicecatalog: endpoint,
                servicecatalogappregistry: endpoint,
                servicediscovery: endpoint,
                servicequotas: endpoint,
                ses: endpoint,
                sesv2: endpoint,
                shield: endpoint,
                signer: endpoint,
                simpledb: endpoint,
                sns: endpoint,
                sqs: endpoint,
                ssm: endpoint,
                ssmcontacts: endpoint,
                ssmincidents: endpoint,
                ssmsap: endpoint,
                sso: endpoint,
                ssoadmin: endpoint,
                stepfunctions: endpoint,
                storagegateway: endpoint,
                sts: endpoint,
                swf: endpoint,
                synthetics: endpoint,
                timestreamwrite: endpoint,
                transcribe: endpoint,
                transcribeservice: endpoint,
                transfer: endpoint,
                verifiedpermissions: endpoint,
                vpclattice: endpoint,
                waf: endpoint,
                wafregional: endpoint,
                wafv2: endpoint,
                wellarchitected: endpoint,
                worklink: endpoint,
                workspaces: endpoint,
                xray: endpoint,
            },
        };
    },
});
