import type { automation } from '@pulumi/pulumi';

/**
 * Options for localstack config.
 */
export interface LocalStackConfigOptions {
    /**
     * LocalStack port.
     * @default 4566
     */
    port?: number;

    /**
     * Region.
     * @default us-east-1
     */
    region?: string;
}

/**
 * Get AWS localstack settings.
 */
export function getAwsLocalStackSettings(options: LocalStackConfigOptions = {}) {
    const port = options.port ?? 4566;
    const region = options.region ?? 'us-east-1';
    const endpoint = `http://localhost:${port}`;
    const config: Record<string, automation.StackSettingsConfigValue> = {
        'aws:region': region,
        'aws:accessKey': 'test',
        'aws:secretKey': 'test',
        'aws:skipCredentialsValidation': 'true',
        'aws:skipRequestingAccountId': 'true',
        'aws:s3UsePathStyle': 'true',
    };

    const endpoints: Record<string, string>[] = [];
    for (const service of AWS_SERVICES) {
        endpoints.push({ [service]: endpoint });
    }

    config['aws:endpoints'] = endpoints;

    return config;
}

const AWS_SERVICES = [
    'accessanalyzer',
    'account',
    'acm',
    'acmpca',
    'amg',
    'amp',
    'amplify',
    'apigateway',
    'apigatewayv2',
    'appautoscaling',
    'appconfig',
    'appfabric',
    'appflow',
    'appintegrations',
    'appintegrationsservice',
    'applicationautoscaling',
    'applicationinsights',
    'appmesh',
    'appregistry',
    'apprunner',
    'appstream',
    'appsync',
    'athena',
    'auditmanager',
    'autoscaling',
    'autoscalingplans',
    'backup',
    'batch',
    'beanstalk',
    'bedrock',
    'bedrockagent',
    'budgets',
    'ce',
    'chime',
    'chimesdkmediapipelines',
    'chimesdkvoice',
    'cleanrooms',
    'cloud9',
    'cloudcontrol',
    'cloudcontrolapi',
    'cloudformation',
    'cloudfront',
    'cloudfrontkeyvaluestore',
    'cloudhsm',
    'cloudhsmv2',
    'cloudsearch',
    'cloudtrail',
    'cloudwatch',
    'cloudwatchevents',
    'cloudwatchevidently',
    'cloudwatchlog',
    'cloudwatchlogs',
    'cloudwatchobservabilityaccessmanager',
    'cloudwatchrum',
    'codeartifact',
    'codebuild',
    'codecatalyst',
    'codecommit',
    'codedeploy',
    'codeguruprofiler',
    'codegurureviewer',
    'codepipeline',
    'codestarconnections',
    'codestarnotifications',
    'cognitoidentity',
    'cognitoidentityprovider',
    'cognitoidp',
    'comprehend',
    'computeoptimizer',
    'config',
    'configservice',
    'connect',
    'connectcases',
    'controltower',
    'costandusagereportservice',
    'costexplorer',
    'costoptimizationhub',
    'cur',
    'customerprofiles',
    'databasemigration',
    'databasemigrationservice',
    'dataexchange',
    'datapipeline',
    'datasync',
    'dax',
    'deploy',
    'detective',
    'devicefarm',
    'directconnect',
    'directoryservice',
    'dlm',
    'dms',
    'docdb',
    'docdbelastic',
    'ds',
    'dynamodb',
    'ec2',
    'ecr',
    'ecrpublic',
    'ecs',
    'efs',
    'eks',
    'elasticache',
    'elasticbeanstalk',
    'elasticloadbalancing',
    'elasticloadbalancingv2',
    'elasticsearch',
    'elasticsearchservice',
    'elastictranscoder',
    'elb',
    'elbv2',
    'emr',
    'emrcontainers',
    'emrserverless',
    'es',
    'eventbridge',
    'events',
    'evidently',
    'finspace',
    'firehose',
    'fis',
    'fms',
    'fsx',
    'gamelift',
    'glacier',
    'globalaccelerator',
    'glue',
    'grafana',
    'greengrass',
    'groundstation',
    'guardduty',
    'healthlake',
    'iam',
    'identitystore',
    'imagebuilder',
    'inspector',
    'inspector2',
    'inspectorv2',
    'internetmonitor',
    'iot',
    'iotanalytics',
    'iotevents',
    'ivs',
    'ivschat',
    'kafka',
    'kafkaconnect',
    'kendra',
    'keyspaces',
    'kinesis',
    'kinesisanalytics',
    'kinesisanalyticsv2',
    'kinesisvideo',
    'kms',
    'lakeformation',
    'lambda',
    'launchwizard',
    'lex',
    'lexmodelbuilding',
    'lexmodelbuildingservice',
    'lexmodels',
    'lexmodelsv2',
    'lexv2models',
    'licensemanager',
    'lightsail',
    'location',
    'locationservice',
    'logs',
    'lookoutmetrics',
    'm2',
    'macie2',
    'managedgrafana',
    'mediaconnect',
    'mediaconvert',
    'medialive',
    'mediapackage',
    'mediapackagev2',
    'mediastore',
    'memorydb',
    'mq',
    'msk',
    'mwaa',
    'neptune',
    'networkfirewall',
    'networkmanager',
    'oam',
    'opensearch',
    'opensearchingestion',
    'opensearchserverless',
    'opensearchservice',
    'opsworks',
    'organizations',
    'osis',
    'outposts',
    'pcaconnectorad',
    'pinpoint',
    'pipes',
    'polly',
    'pricing',
    'prometheus',
    'prometheusservice',
    'qbusiness',
    'qldb',
    'quicksight',
    'ram',
    'rbin',
    'rds',
    'recyclebin',
    'redshift',
    'redshiftdata',
    'redshiftdataapiservice',
    'redshiftserverless',
    'rekognition',
    'resourceexplorer2',
    'resourcegroups',
    'resourcegroupstagging',
    'resourcegroupstaggingapi',
    'rolesanywhere',
    'route53',
    'route53domains',
    'route53recoverycontrolconfig',
    'route53recoveryreadiness',
    'route53resolver',
    'rum',
    's3',
    's3api',
    's3control',
    's3outposts',
    'sagemaker',
    'scheduler',
    'schemas',
    'sdb',
    'secretsmanager',
    'securityhub',
    'securitylake',
    'serverlessapplicationrepository',
    'serverlessapprepo',
    'serverlessrepo',
    'servicecatalog',
    'servicecatalogappregistry',
    'servicediscovery',
    'servicequotas',
    'ses',
    'sesv2',
    'sfn',
    'shield',
    'signer',
    'simpledb',
    'sns',
    'sqs',
    'ssm',
    'ssmcontacts',
    'ssmincidents',
    'ssmsap',
    'sso',
    'ssoadmin',
    'stepfunctions',
    'storagegateway',
    'sts',
    'swf',
    'synthetics',
    'timestreamwrite',
    'transcribe',
    'transcribeservice',
    'transfer',
    'verifiedpermissions',
    'vpclattice',
    'waf',
    'wafregional',
    'wafv2',
    'wellarchitected',
    'worklink',
    'workspaces',
    'xray',
];
