import { readFile } from 'node:fs/promises';
import { basename } from 'node:path';

import { saveFile } from '@nzyme/project-utils/saveFile.js';

import { compileTranslations } from './compileTranslations.js';
import type { TranslationResult } from './compileTranslations.js';

/**
 * Result of translation file compilation
 */
export interface CompileTranslationFileResult {
    /**
     * Compilation errors found
     */
    errors: TranslationResult['errors'];
    /**
     * Path where the output was saved
     */
    outputPath: string;
    /**
     * Whether compilation was successful (no errors)
     */
    success: boolean;
}

/**
 * Compile a translation YAML file to TypeScript with formatting and ESLint fixes
 * @param inputPath - The absolute path to the input YAML file
 * @param outputPath - The absolute path to the output TypeScript file
 * @__NO_SIDE_EFFECTS__
 */
export async function compileTranslationFile(
    inputPath: string,
    outputPath: string,
): Promise<CompileTranslationFileResult> {
    // Read the input YAML file
    const yamlContent = await readFile(inputPath, 'utf-8');

    // Compile the translations
    const result = compileTranslations(yamlContent);

    // Add header comment to generated code
    const sourceFileName = basename(inputPath);
    const header = `/**\n * This file is auto-generated from ${sourceFileName}\n * Do not edit this file directly. Edit the source file instead.\n */\n\n`;
    const codeWithHeader = header + result.code;

    // Save the compiled code with formatting and ESLint fixes
    await saveFile(outputPath, codeWithHeader);

    return {
        errors: result.errors,
        success: result.errors.length === 0,
        outputPath,
    };
}
