import { join } from 'node:path';

import type { Package } from '@nzyme/project-utils/getPackages.js';
import { describe, expect, it } from 'bun:test';

import { getIndexSettings } from './IndexSettings.js';
import type { IndexSymbol } from './IndexSymbol.js';
import { renderMarkdown } from './renderMarkdown.js';

const ROOT = '/repo';

/** `@acme/utils` feeds UTILS.md; entities and an `actor` kind are configured. */
const settings = getIndexSettings({
    globalUtilPackages: ['@acme/utils'],
    defineKinds: [{ kind: 'actor', section: 'Actors', callee: 'defineActor', nameKey: 'type', order: 40 }],
    entities: { tableFunctions: ['pgTable'] },
});

type SymbolOverrides = Partial<IndexSymbol> & Pick<IndexSymbol, 'exportName' | 'kind' | 'packageName'>;

function pkg(name: string, path: string, description?: string): Package {
    return { path, packageJson: { name, description } };
}

function symbol(overrides: SymbolOverrides): IndexSymbol {
    return {
        importPath: `${overrides.packageName}/${overrides.exportName}.js`,
        internalName: null,
        description: null,
        signature: null,
        relPath: join('packages', 'pkg', 'src', `${overrides.exportName}.ts`),
        ...overrides,
    };
}

describe('renderMarkdown', () => {
    it('lists every package sorted by name in the root INDEX.md, incl. a zero-symbol one, with a UTILS.md link', () => {
        const packages = [
            pkg('@acme/zeta', join(ROOT, 'packages/zeta'), 'The zeta package.'),
            pkg('@acme/alpha', join(ROOT, 'packages/alpha'), 'The alpha package.'),
            pkg('@acme/empty', join(ROOT, 'packages/empty')),
        ];
        const symbols: IndexSymbol[] = [
            symbol({ kind: 'service', packageName: '@acme/alpha', exportName: 'AlphaService' }),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols, settings });

        const rootIndex = files.get(join(ROOT, 'INDEX.md'));
        expect(rootIndex).toBeDefined();
        const lines = rootIndex!.split('\n');
        expect(lines[0]).toBe('<!-- AUTOGENERATED by `bun index` — do not edit. Run `bun index` to regenerate. -->');

        // Packages appear sorted by name: alpha, empty, zeta.
        const alphaLine = rootIndex!.indexOf('@acme/alpha');
        const emptyLine = rootIndex!.indexOf('@acme/empty');
        const zetaLine = rootIndex!.indexOf('@acme/zeta');
        expect(alphaLine).toBeGreaterThan(-1);
        expect(emptyLine).toBeGreaterThan(-1);
        expect(zetaLine).toBeGreaterThan(-1);
        expect(alphaLine).toBeLessThan(emptyLine);
        expect(emptyLine).toBeLessThan(zetaLine);

        // Zero-symbol package still listed, with no description shown as a placeholder.
        expect(rootIndex).toContain('packages/empty');
        expect(rootIndex).toContain('_(no description)_');

        // Alpha has a per-package INDEX.md (it has a non-util symbol) and root links to it.
        expect(rootIndex).toContain(join('packages', 'alpha', 'INDEX.md').replaceAll('\\', '/'));

        // Root links to UTILS.md.
        expect(rootIndex).toContain('UTILS.md');

        expect(files.has(join(ROOT, 'UTILS.md'))).toBe(true);
    });

    it('groups util symbols by package in UTILS.md, showing signature and importPath', () => {
        const packages = [pkg('@acme/utils', join(ROOT, 'packages/utils'))];
        const symbols: IndexSymbol[] = [
            symbol({
                kind: 'util',
                packageName: '@acme/utils',
                exportName: 'clamp',
                importPath: '@acme/utils/clamp.js',
                description: 'Clamps a number.',
                signature: 'clamp(v: number): number',
            }),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols, settings });

        const utils = files.get(join(ROOT, 'UTILS.md'));
        expect(utils).toBeDefined();
        expect(utils!.split('\n')[0]).toBe(
            '<!-- AUTOGENERATED by `bun index` — do not edit. Run `bun index` to regenerate. -->',
        );
        expect(utils).toContain('## @acme/utils');
        expect(utils).toContain('clamp(v: number): number');
        expect(utils).toContain('Clamps a number.');
        expect(utils).toContain('@acme/utils/clamp.js');

        // A util-only package now also gets a per-package INDEX.md (with a Utils section).
        const pkgIndex = files.get(join(ROOT, 'packages/utils', 'INDEX.md'));
        expect(pkgIndex).toBeDefined();
        expect(pkgIndex).toContain('## Utils');
        expect(pkgIndex).toContain('clamp(v: number): number');
    });

    it('narrows UTILS.md to foundational packages, excluding a non-global package (which keeps it in its own INDEX.md only)', () => {
        const packages = [
            pkg('@acme/utils', join(ROOT, 'packages/utils')),
            pkg('@acme/backend', join(ROOT, 'packages/backend')),
        ];
        const symbols: IndexSymbol[] = [
            symbol({
                kind: 'util',
                packageName: '@acme/utils',
                exportName: 'clamp',
                importPath: '@acme/utils/clamp.js',
                signature: 'clamp(v: number): number',
            }),
            symbol({
                kind: 'util',
                packageName: '@acme/backend',
                exportName: 'shardKeyOf',
                importPath: '@acme/backend/shardKeyOf.js',
                signature: 'shardKeyOf(id: string): number',
            }),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols, settings });

        const utils = files.get(join(ROOT, 'UTILS.md'));
        expect(utils).toBeDefined();
        expect(utils).toContain('@acme/utils');
        expect(utils).toContain('clamp(v: number): number');
        expect(utils).not.toContain('shardKeyOf');
        expect(utils).not.toContain('@acme/backend');

        // The non-global package's util still shows up in its own package INDEX.md Utils section.
        const backendIndex = files.get(join(ROOT, 'packages/backend', 'INDEX.md'));
        expect(backendIndex).toBeDefined();
        expect(backendIndex).toContain('## Utils');
        expect(backendIndex).toContain('shardKeyOf(id: string): number');
    });

    it('renders a package INDEX.md with Services before Endpoints, showing the endpoint RPC name', () => {
        const packages = [pkg('@acme/api', join(ROOT, 'packages/api'), 'The API package.')];
        const symbols: IndexSymbol[] = [
            symbol({
                kind: 'endpoint',
                packageName: '@acme/api',
                exportName: 'OrderGetEndpoint',
                internalName: 'OrderGet',
            }),
            symbol({
                kind: 'service',
                packageName: '@acme/api',
                exportName: 'OrderService',
            }),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols, settings });

        const pkgIndex = files.get(join(ROOT, 'packages/api', 'INDEX.md'));
        expect(pkgIndex).toBeDefined();
        expect(pkgIndex!.split('\n')[0]).toBe(
            '<!-- AUTOGENERATED by `bun index` — do not edit. Run `bun index` to regenerate. -->',
        );

        const servicesIdx = pkgIndex!.indexOf('## Services');
        const endpointsIdx = pkgIndex!.indexOf('## Endpoints');
        expect(servicesIdx).toBeGreaterThan(-1);
        expect(endpointsIdx).toBeGreaterThan(-1);
        expect(servicesIdx).toBeLessThan(endpointsIdx);

        expect(pkgIndex).toContain('OrderGetEndpoint');
        expect(pkgIndex).toContain('name: `OrderGet`');
    });

    it('renders Entities with the table name for a package with an entity symbol', () => {
        const packages = [pkg('@acme/database', join(ROOT, 'packages/database'))];
        const symbols: IndexSymbol[] = [
            symbol({
                kind: 'entity',
                packageName: '@acme/database',
                exportName: 'payment',
                internalName: 'payment',
                importPath: '@acme/database/schema/payment.js',
            }),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols, settings });

        const pkgIndex = files.get(join(ROOT, 'packages/database', 'INDEX.md'));
        expect(pkgIndex).toBeDefined();
        expect(pkgIndex).toContain('## Entities');
        expect(pkgIndex).toContain('table: `payment`');
    });

    it('renders a package Utils section last (after Entities), signature-first like UTILS.md', () => {
        const packages = [pkg('@acme/database', join(ROOT, 'packages/database'))];
        const symbols: IndexSymbol[] = [
            symbol({
                kind: 'entity',
                packageName: '@acme/database',
                exportName: 'payment',
                internalName: 'payment',
                importPath: '@acme/database/schema/payment.js',
            }),
            symbol({
                kind: 'util',
                packageName: '@acme/database',
                exportName: 'shardKeyOf',
                importPath: '@acme/database/shardKeyOf.js',
                description: 'Computes a shard key.',
                signature: 'shardKeyOf(id: string): number',
            }),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols, settings });

        const pkgIndex = files.get(join(ROOT, 'packages/database', 'INDEX.md'));
        expect(pkgIndex).toBeDefined();

        const entitiesIdx = pkgIndex!.indexOf('## Entities');
        const utilsIdx = pkgIndex!.indexOf('## Utils');
        expect(entitiesIdx).toBeGreaterThan(-1);
        expect(utilsIdx).toBeGreaterThan(-1);
        expect(entitiesIdx).toBeLessThan(utilsIdx);

        // Signature-first row style, same as the global UTILS.md.
        expect(pkgIndex).toContain(
            '- `shardKeyOf(id: string): number` — Computes a shard key. (`@acme/database/shardKeyOf.js`)',
        );
    });

    it('emits a per-package file (with a Utils section) and a root link for a package whose only symbol is a util', () => {
        const packages = [pkg('@acme/backend', join(ROOT, 'packages/backend'))];
        const symbols: IndexSymbol[] = [
            symbol({
                kind: 'util',
                packageName: '@acme/backend',
                exportName: 'clamp',
                importPath: '@acme/backend/clamp.js',
                signature: 'clamp(v: number): number',
            }),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols, settings });

        const pkgIndex = files.get(join(ROOT, 'packages/backend', 'INDEX.md'));
        expect(pkgIndex).toBeDefined();
        expect(pkgIndex).toContain('## Utils');
        expect(pkgIndex).toContain('clamp(v: number): number');

        const rootIndex = files.get(join(ROOT, 'INDEX.md'));
        expect(rootIndex).toContain(join('packages', 'backend', 'INDEX.md').replaceAll('\\', '/'));
    });

    it('produces a byte-identical Map when the same symbols are rendered in shuffled order (determinism)', () => {
        const packages = [
            pkg('@acme/zeta', join(ROOT, 'packages/zeta'), 'Zeta.'),
            pkg('@acme/alpha', join(ROOT, 'packages/alpha'), 'Alpha.'),
        ];
        const symbols: IndexSymbol[] = [
            symbol({ kind: 'service', packageName: '@acme/alpha', exportName: 'BService' }),
            symbol({ kind: 'service', packageName: '@acme/alpha', exportName: 'AService' }),
            symbol({ kind: 'endpoint', packageName: '@acme/zeta', exportName: 'ZEndpoint', internalName: 'Z' }),
            symbol({
                kind: 'util',
                packageName: '@acme/alpha',
                exportName: 'helperB',
                signature: 'helperB(): void',
            }),
            symbol({
                kind: 'util',
                packageName: '@acme/alpha',
                exportName: 'helperA',
                signature: 'helperA(): void',
            }),
        ];
        const shuffledSymbols = symbols.toReversed();
        const shuffledPackages = packages.toReversed();

        const a = renderMarkdown({ root: ROOT, packages, symbols, settings });
        const b = renderMarkdown({ root: ROOT, packages: shuffledPackages, symbols: shuffledSymbols, settings });

        expect(a.size).toBe(b.size);
        for (const [key, content] of a) {
            expect(b.get(key)).toBe(content);
        }

        // Re-rendering the same input again is also byte-identical (idempotency).
        const c = renderMarkdown({ root: ROOT, packages, symbols, settings });
        for (const [key, content] of a) {
            expect(c.get(key)).toBe(content);
        }
    });

    it('skips packages with no name', () => {
        const packages = [
            { path: join(ROOT, 'packages/anon'), packageJson: {} },
            pkg('@acme/named', join(ROOT, 'packages/named'), 'Named.'),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols: [], settings });

        const rootIndex = files.get(join(ROOT, 'INDEX.md'));
        expect(rootIndex).not.toContain('packages/anon');
        expect(rootIndex).toContain('@acme/named');
    });

    it('renders a configured kind in its configured place, labelled with its name key', () => {
        const packages = [pkg('@acme/chat', join(ROOT, 'packages/chat'))];
        const symbols: IndexSymbol[] = [
            symbol({ kind: 'endpoint', packageName: '@acme/chat', exportName: 'ChatEndpoint', internalName: 'Chat' }),
            symbol({ kind: 'actor', packageName: '@acme/chat', exportName: 'ChatActor', internalName: 'chat' }),
            symbol({ kind: 'factory', packageName: '@acme/chat', exportName: 'ChatFactory', internalName: 'Chat' }),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols, settings });

        const pkgIndex = files.get(join(ROOT, 'packages/chat', 'INDEX.md')) ?? '';
        const factoriesIdx = pkgIndex.indexOf('## Factories');
        const actorsIdx = pkgIndex.indexOf('## Actors');
        const endpointsIdx = pkgIndex.indexOf('## Endpoints');
        expect(factoriesIdx).toBeGreaterThan(-1);
        expect(factoriesIdx).toBeLessThan(actorsIdx);
        expect(actorsIdx).toBeLessThan(endpointsIdx);
        expect(pkgIndex).toContain('type: `chat`');
    });

    it('lists the indexed kinds in the root INDEX.md preamble', () => {
        const files = renderMarkdown({ root: ROOT, packages: [], symbols: [], settings });

        expect(files.get(join(ROOT, 'INDEX.md'))).toContain(
            'listing its services, commands, factories, actors, endpoints, components, entities, and `@util` helpers',
        );
    });

    it('writes no UTILS.md and does not link it when no global util packages are configured', () => {
        const packages = [pkg('@acme/utils', join(ROOT, 'packages/utils'))];
        const symbols: IndexSymbol[] = [
            symbol({ kind: 'util', packageName: '@acme/utils', exportName: 'clamp', signature: 'clamp(): void' }),
        ];

        const files = renderMarkdown({ root: ROOT, packages, symbols, settings: getIndexSettings({}) });

        expect(files.has(join(ROOT, 'UTILS.md'))).toBe(false);
        const rootIndex = files.get(join(ROOT, 'INDEX.md'));
        expect(rootIndex).not.toContain('UTILS.md');
        expect(rootIndex).toContain(
            'listing its services, commands, factories, endpoints, components, and `@util` helpers',
        );
        expect(files.get(join(ROOT, 'packages/utils', 'INDEX.md'))).toContain('clamp(): void');
    });
});
