import { join, relative } from 'node:path';

import type { Package } from '@nzyme/project-utils/getPackages.js';
import { groupByToMap } from '@nzyme/utils/array/groupByToMap.js';

import type { IndexSettings } from './IndexSettings.js';
import { EXTRA_SECTIONS } from './IndexSettings.js';
import type { IndexSymbol } from './IndexSymbol.js';

/** Inputs for {@link renderMarkdown}. */
export interface RenderMarkdownOptions {
    /** Repo root — file paths in the returned map are absolute, rooted here. */
    root: string;
    /** All workspace packages (from `getPackages`); rendered sorted by name regardless of input order. */
    packages: readonly Package[];
    /** All collected symbols; grouped/sorted by section then export name regardless of input order. */
    symbols: readonly IndexSymbol[];
    /** The settings the symbols were collected with — sections, labels and the `UTILS.md` packages. */
    settings: IndexSettings;
}

/** How a kind renders in a package's `INDEX.md`. */
interface SectionInfo {
    /** Section heading, e.g. 'Services'. */
    section: string;
    /** Ascending position among the sections. */
    order: number;
    /** Label prefixing a row's internal name, e.g. 'name' — null for kinds without one. */
    nameLabel: string | null;
}

/** A package together with its (guaranteed-present) name. */
interface NamedPackage {
    name: string;
    pkg: Package;
}

/** First line of every generated file — marks it as generated and gitignore-able. */
const HEADER = '<!-- AUTOGENERATED by `bun index` — do not edit. Run `bun index` to regenerate. -->';

/**
 * Renders every collected symbol into a fixed set of deterministic Markdown files: a root
 * `INDEX.md` (package hub), a root `UTILS.md` (curated global subset of `@util` helpers from the
 * configured foundational packages — omitted when none are configured), and one `INDEX.md` per
 * package that has at least one symbol of any kind (including `util` — every package's own `@util`
 * helpers render in its `INDEX.md` Utils section regardless of whether the package is
 * foundational). Pure — same inputs always produce a byte-identical result regardless of
 * `packages`/`symbols` input order, since every list is sorted before rendering (never relies on
 * Map/object iteration of unsorted data, never reads the clock or filesystem).
 * @returns Absolute file path → file contents, ready to be written as-is.
 * @__NO_SIDE_EFFECTS__
 */
export function renderMarkdown(options: RenderMarkdownOptions): Map<string, string> {
    const { root, packages, symbols, settings } = options;

    const sections = getSections(settings);
    const hasUtilsFile = settings.globalUtilPackages.size > 0;

    const sortedPackages: NamedPackage[] = [];
    for (const pkg of packages) {
        if (pkg.packageJson.name) {
            sortedPackages.push({ name: pkg.packageJson.name, pkg });
        }
    }
    sortedPackages.sort((a, b) => a.name.localeCompare(b.name));

    const symbolsByPackage = groupByToMap(symbols, (symbol) => symbol.packageName);

    const files = new Map<string, string>([[join(root, 'INDEX.md'), renderRootIndex()]]);
    if (hasUtilsFile) {
        files.set(join(root, 'UTILS.md'), renderUtils());
    }

    for (const { name, pkg } of sortedPackages) {
        const packageSymbols = symbolsByPackage.get(name);
        if (packageSymbols) {
            files.set(join(pkg.path, 'INDEX.md'), renderPackageIndex(name, pkg, packageSymbols));
        }
    }

    return files;

    /** Renders the root `INDEX.md`: preamble + a sorted list of every named package. */
    function renderRootIndex(): string {
        const kinds = describeIndexedKinds(sections);
        const preamble = hasUtilsFile
            ? 'Two kinds of generated index live in this repo: each package has its own `INDEX.md` listing its' +
              ` ${kinds} under section headers; the global [\`UTILS.md\`](./UTILS.md) lists the context-agnostic` +
              ' subset of `@util` helpers from the foundational util packages — check both before writing a new' +
              ' utility.'
            : `Each package with indexed symbols has its own \`INDEX.md\` listing its ${kinds} under section` +
              ' headers — check them before writing a new utility.';

        const lines = [HEADER, '', '# Project Index', '', preamble, '', '## Packages', ''];

        for (const { name, pkg } of sortedPackages) {
            const packagePath = toPosixPath(relative(root, pkg.path));
            const description = pkg.packageJson.description || '_(no description)_';
            const link = symbolsByPackage.has(name)
                ? ` — [INDEX.md](./${toPosixPath(relative(root, join(pkg.path, 'INDEX.md')))})`
                : '';
            lines.push(`- **${name}** (\`${packagePath}\`): ${description}${link}`);
        }

        lines.push('');
        if (hasUtilsFile) {
            lines.push('See [`UTILS.md`](./UTILS.md) for reusable helpers.', '');
        }

        return lines.join('\n');
    }

    /**
     * Renders the root `UTILS.md`: `util` symbols from the configured foundational packages only,
     * grouped by package and sorted within each group. Every package's own `@util` helpers
     * (foundational or not) also render in that package's `INDEX.md` Utils section via {@link renderUtilRow}.
     */
    function renderUtils(): string {
        const utilSymbols = symbols.filter(
            symbol => symbol.kind === 'util' && settings.globalUtilPackages.has(symbol.packageName),
        );
        const groups = groupByToMap(utilSymbols, (symbol) => symbol.packageName);
        const packageNames = [...groups.keys()].toSorted((a, b) => a.localeCompare(b));

        const lines = [
            HEADER,
            '',
            '# Utilities',
            '',
            'Context-agnostic helpers from the foundational util packages, reusable across the whole repo — ' +
                'reuse before writing your own. Every package additionally lists its own `@util` helpers under ' +
                "a Utils section in that package's `INDEX.md`.",
            '',
        ];

        for (const packageName of packageNames) {
            lines.push(`## ${packageName}`, '');
            const rows = (groups.get(packageName) ?? []).toSorted(compareSymbols);
            for (const row of rows) {
                lines.push(renderUtilRow(row));
            }
            lines.push('');
        }

        return lines.join('\n');
    }

    /** Renders one package's `INDEX.md`: header + fixed-order sections, each with sorted rows. */
    function renderPackageIndex(packageName: string, pkg: Package, packageSymbols: readonly IndexSymbol[]): string {
        const packagePath = toPosixPath(relative(root, pkg.path));
        const description = pkg.packageJson.description || '_(no description)_';

        const lines = [HEADER, '', `# ${packageName}`, '', description, '', `Path: \`${packagePath}\``, ''];

        const byKind = groupByToMap(packageSymbols, (symbol) => symbol.kind);

        const kinds = [...byKind.keys()].toSorted(
            (a, b) => (sections.get(a)?.order ?? 0) - (sections.get(b)?.order ?? 0),
        );

        for (const kind of kinds) {
            const section = sections.get(kind);
            const rows = (byKind.get(kind) ?? []).toSorted(compareSymbols);

            lines.push(`## ${section?.section ?? kind}`, '');
            for (const row of rows) {
                lines.push(kind === 'util' ? renderUtilRow(row) : renderRow(row, section?.nameLabel ?? null));
            }
            lines.push('');
        }

        return lines.join('\n');
    }
}

/**
 * How every kind the settings produce renders, keyed by kind: the `defineX` kinds labelled by their
 * name key, then components, entities (only when configured, labelled `table`) and utils — Utils last.
 */
function getSections(settings: IndexSettings): Map<string, SectionInfo> {
    const sections = new Map<string, SectionInfo>();

    for (const kind of settings.defineKinds) {
        sections.set(kind.kind, { section: kind.section, order: kind.order, nameLabel: kind.nameKey });
    }

    sections.set('component', { ...EXTRA_SECTIONS.component, nameLabel: null });
    if (settings.entities) {
        sections.set('entity', { ...EXTRA_SECTIONS.entity, nameLabel: 'table' });
    }
    sections.set('util', { ...EXTRA_SECTIONS.util, nameLabel: null });

    return sections;
}

/** Lists the sections a package `INDEX.md` can have, in order, e.g. "services, commands, and `@util` helpers". */
function describeIndexedKinds(sections: ReadonlyMap<string, SectionInfo>): string {
    const names: string[] = [];
    for (const [kind, info] of [...sections].toSorted(([, a], [, b]) => a.order - b.order)) {
        names.push(kind === 'util' ? '`@util` helpers' : info.section.toLowerCase());
    }

    const last = names.pop();
    return names.length > 0 ? `${names.join(', ')}, and ${last}` : String(last);
}

/** Renders a single symbol as one Markdown list row: bold export name, importPath, label, description. */
function renderRow(row: IndexSymbol, nameLabel: string | null): string {
    const parts = [`**${row.exportName}**`, `\`${row.importPath}\``];

    if (nameLabel && row.internalName) {
        parts.push(`${nameLabel}: \`${row.internalName}\``);
    }

    if (row.description) {
        parts.push(row.description);
    }

    return `- ${parts.join(' — ')}`;
}

/**
 * Renders a `util`-kind symbol as one signature-first Markdown list row — shared by the global
 * `UTILS.md` and every package's own `INDEX.md` Utils section, so a helper reads identically in both.
 */
function renderUtilRow(row: IndexSymbol): string {
    const signature = row.signature ? `\`${row.signature}\`` : `**${row.exportName}**`;
    const description = row.description ? ` — ${row.description}` : '';
    return `- ${signature}${description} (\`${row.importPath}\`)`;
}

/**
 * Orders rows by export name, then import path — the tie-break matters for same-named variants
 * (`randomInt` in `.node.ts` and `.browser.ts`), which would otherwise keep their discovery order,
 * and discovery runs concurrently.
 */
function compareSymbols(a: IndexSymbol, b: IndexSymbol): number {
    return a.exportName.localeCompare(b.exportName) || a.importPath.localeCompare(b.importPath);
}

/** Normalizes a path to forward slashes so generated Markdown links are OS-independent. */
function toPosixPath(path: string): string {
    return path.replaceAll('\\', '/');
}
