/**
 * This file is auto-generated from mixed-translations.yaml
 * Do not edit this file directly. Edit the source file instead.
 */

import type { PluralTranslation } from '@nzyme/i18n-core/pluralization.js';
import { pluralizationEn, pluralizationPl } from '@nzyme/i18n-core/pluralizationRules.js';
import type { Translation } from '@nzyme/i18n-core/Translation.js';

export const greeting: Translation<{ name: unknown }> = (lang, params) => {
    switch (lang) {
        case 'en':
            return ['Hello ', params.name, '!'];
        case 'pl':
            return ['Witaj ', params.name, '!'];
    }
};

const itemsCount_pl: PluralTranslation<typeof pluralizationPl, { count: number }> = {
    zero: () => 'brak elementów',
    one: () => 'jeden element',
    few: params => [params.count, ' elementy'],
    many: params => [params.count, ' elementów'],
};

const itemsCount_en: PluralTranslation<typeof pluralizationEn, { count: number }> = {
    zero: () => 'no items',
    one: () => 'one item',
    many: params => [params.count, ' items'],
};

export const itemsCount: Translation<{ count: number }> = (lang, params) => {
    switch (lang) {
        case 'en':
            return pluralizationEn.pluralize(params.count, itemsCount_en)?.(params);
        case 'pl':
            return pluralizationPl.pluralize(params.count, itemsCount_pl)?.(params);
    }
};

export const farewell: Translation = lang => {
    switch (lang) {
        case 'en':
            return 'Goodbye!';
        case 'pl':
            return 'Do widzenia!';
    }
};
