/**
 * This file is auto-generated from pluralization-basic.yaml
 * Do not edit this file directly. Edit the source file instead.
 */

import { pluralizationPl, pluralizationEn } from '@nzyme/i18n-core/pluralizationRules.js';
import type { Translation } from '@nzyme/i18n-core/Translation.js';
import type { PluralTranslation } from '@nzyme/i18n-core/pluralization.js';

const applesCount_pl: PluralTranslation<typeof pluralizationPl, { count: number; container: unknown }> = {
    zero: params => ['zero jabłek w ', params.container],
    one: params => ['jedno jabłko w ', params.container],
    few: params => [params.count, ' jabłka w ', params.container],
    many: params => [params.count, ' jabłek w ', params.container],
};

const applesCount_en: PluralTranslation<typeof pluralizationEn, { count: number; container: unknown }> = {
    zero: params => ['no apples in ', params.container],
    one: params => ['one apple in ', params.container],
    many: params => [params.count, ' apples in ', params.container],
};

export const applesCount: Translation<{ count: number; container: unknown }> = (lang, params) => {
    switch (lang) {
        case 'pl':
            return pluralizationPl.pluralize(params.count, applesCount_pl)?.(params);
        case 'en':
            return pluralizationEn.pluralize(params.count, applesCount_en)?.(params);
    }
};
