/**
 * This file is auto-generated from pluralization-czech.yaml
 * Do not edit this file directly. Edit the source file instead.
 */

import { pluralizationCs, pluralizationEn, type Translation, type PluralTranslation } from '@nzyme/i18n-core';

const itemsCount_cs: PluralTranslation<typeof pluralizationCs, { count: number }> = {
    zero: () => 'žádné položky',
    one: () => 'jedna položka',
    few: params => [params.count, ' položky'],
    many: params => [params.count, ' položek'],
};

const itemsCount_en: PluralTranslation<typeof pluralizationEn, { count: number }> = {
    zero: () => 'no items',
    one: () => 'one item',
    many: params => [params.count, ' items'],
};

export const itemsCount: Translation<{ count: number }> = (lang, params) => {
    switch (lang) {
        case 'cs':
            return pluralizationCs.pluralize(params.count, itemsCount_cs)?.(params);
        case 'en':
            return pluralizationEn.pluralize(params.count, itemsCount_en)?.(params);
    }
};
