/**
 * This file is auto-generated from reserved-words.yaml
 * Do not edit this file directly. Edit the source file instead.
 */

import type { PluralTranslation } from '@nzyme/i18n-core/pluralization.js';
import { pluralizationEn, pluralizationPl } from '@nzyme/i18n-core/pluralizationRules.js';
import type { Translation } from '@nzyme/i18n-core/Translation.js';

const default$: Translation = lang => {
    switch (lang) {
        case 'en':
            return 'Default';
        case 'pl':
            return 'Domyslne';
    }
};

const const$: Translation = lang => {
    switch (lang) {
        case 'en':
            return 'Constant';
        case 'pl':
            return 'Stala';
    }
};

const export$: Translation<{ name: unknown }> = (lang, params) => {
    switch (lang) {
        case 'en':
            return ['Export ', params.name];
        case 'pl':
            return ['Eksport ', params.name];
    }
};

const class$_pl: PluralTranslation<typeof pluralizationPl, { count: number }> = {
    zero: () => 'brak klas',
    one: () => 'jedna klasa',
    few: params => [params.count, ' klasy'],
    many: params => [params.count, ' klas'],
};

const class$_en: PluralTranslation<typeof pluralizationEn, { count: number }> = {
    zero: () => 'no classes',
    one: () => 'one class',
    many: params => [params.count, ' classes'],
};

const class$: Translation<{ count: number }> = (lang, params) => {
    switch (lang) {
        case 'en':
            return pluralizationEn.pluralize(params.count, class$_en)?.(params);
        case 'pl':
            return pluralizationPl.pluralize(params.count, class$_pl)?.(params);
    }
};

export { class$ as class, const$ as const, default$ as default, export$ as export };
