/**
 * This file is auto-generated from reserved-words.yaml
 * Do not edit this file directly. Edit the source file instead.
 */

import {
  pluralizationPl,
  pluralizationEn,
  type Translation,
  type PluralTranslation,
} from "@nzyme/i18n-core";

const default$: Translation = (lang) => {
  switch (lang) {
    case "pl":
      return "Domyslne";
    case "en":
      return "Default";
  }
};

const const$: Translation = (lang) => {
  switch (lang) {
    case "pl":
      return "Stala";
    case "en":
      return "Constant";
  }
};

const export$: Translation<{ name: unknown }> = (lang, params) => {
  switch (lang) {
    case "pl":
      return ["Eksport ", params.name];
    case "en":
      return ["Export ", params.name];
  }
};

const class$_pl: PluralTranslation<typeof pluralizationPl, { count: number }> = {
  zero: () => "brak klas",
  one: () => "jedna klasa",
  few: (params) => [params.count, " klasy"],
  many: (params) => [params.count, " klas"],
};

const class$_en: PluralTranslation<typeof pluralizationEn, { count: number }> = {
  zero: () => "no classes",
  one: () => "one class",
  many: (params) => [params.count, " classes"],
};

const class$: Translation<{ count: number }> = (lang, params) => {
  switch (lang) {
    case "pl":
      return pluralizationPl.pluralize(params.count, class$_pl)?.(params);
    case "en":
      return pluralizationEn.pluralize(params.count, class$_en)?.(params);
  }
};

export { default$ as default, const$ as const, export$ as export, class$ as class };
