import * as fs from 'fs/promises';
import * as path from 'path';

import chalk from 'chalk';
import { watch } from 'chokidar';
import glob from 'fast-glob';
import * as fsExtra from 'fs-extra';

import { Option } from '@nzyme/cli';
import { Command } from '@nzyme/cli/Command.js';
import { isFileIgnored } from '@nzyme/project-utils/isFileIgnored.js';

import { generateSchemaFromFile } from '../../generateSchema.js';
import { getSchemaOutputPath } from '../../output/generateSchemaFile.js';

const TYPE_REGEX = /\.type\.ts$/;

/**
 * Command to generate schemas from TypeScript type files
 */
export class ZchemaCommand extends Command {
    static override paths = [['generate'], []];

    static override usage = Command.Usage({
        category: 'Schema',
        description: 'Generate sury schemas from TypeScript type files',
    });

    watch = Option.Boolean('--watch,-w', {
        description: 'Watch for changes and regenerate schemas automatically',
    });

    cwd = process.cwd();

    /**
     * Execute the command
     */
    override async run() {
        const files = await glob('**/*.type.ts', {
            cwd: this.cwd,
            ignore: ['node_modules', 'dist', 'build'],
        });

        if (files.length === 0) {
            this.logger.info('No *.type.ts files found');
            return 0;
        }

        this.logger.info(`Found ${files.length} type file(s) to process`);

        const results = await Promise.all(files.map(file => this.generateSchemaFile(file)));

        if (this.watch) {
            this.startWatcher();
        }

        const failedCount = results.filter(result => !result).length;
        if (failedCount > 0) {
            this.logger.error(`Failed to generate schemas for ${failedCount} file(s)`);
            return 1;
        }

        this.logger.info(`✅ Successfully generated schemas for ${results.length} file(s)`);
        return 0;
    }

    private startWatcher() {
        const watcher = watch('.', {
            cwd: this.cwd,
            ignored: file => {
                const ignored = isFileIgnored(file);
                if (ignored === false) {
                    // It is a non-ignored file, so we need to check if it matches the TYPE_REGEX
                    return !TYPE_REGEX.test(file);
                }

                return !!ignored;
            },
            ignoreInitial: true,
            persistent: true,
        });

        this.logger.info('👀 Watching for changes...');

        watcher.on('add', file => void this.onAddFile(file));
        watcher.on('change', file => void this.onAddFile(file));
        watcher.on('unlink', file => void this.onDeleteFile(file));
    }

    private async onAddFile(file: string) {
        if (!TYPE_REGEX.test(file)) {
            return;
        }

        await this.generateSchemaFile(file);
    }

    private async onDeleteFile(file: string) {
        if (!TYPE_REGEX.test(file)) {
            return;
        }

        const outputPath = this.toSchemaPath(file);

        try {
            await fsExtra.remove(outputPath);
            this.logger.info(`🗑️  Removed ${chalk.yellow(outputPath)}`);
        } catch (error) {
            this.logger.error(`❌ Failed to remove ${outputPath}`, { error });
        }
    }

    private async generateSchemaFile(file: string): Promise<boolean> {
        try {
            const absolutePath = this.toAbsolute(file);

            // Check if file exists
            try {
                await fs.access(absolutePath);
            } catch {
                this.logger.warn(`⚠️  File not found: ${chalk.yellow(file)}`);
                return false;
            }

            const result = await generateSchemaFromFile({
                inputPath: absolutePath,
                headerComment: `Generated by zchema from ${file}`,
            });

            this.logger.info(
                `📝 Generated schema: ${chalk.green(file)} → ${chalk.blue(path.relative(this.cwd, result.outputPath))}`,
            );

            if (result.count > 0) {
                this.logger.info(`   └─ ${result.count} schema(s) generated`);
            }

            return true;
        } catch (error) {
            this.logger.error(`❌ Failed to generate schema for ${file}`, { error });
            return false;
        }
    }

    private toAbsolute(file: string) {
        return path.isAbsolute(file) ? file : path.join(this.cwd, file);
    }

    private toSchemaPath(file: string) {
        const absolutePath = this.toAbsolute(file);
        return getSchemaOutputPath(absolutePath);
    }
}
