name: Release to NPM
on:
    push:
        branches: [release]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts
            - run: yarn install
            - run: yarn turbo run build
            - run: yarn test
            - run: yarn release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
